# Create preprocess() function that will take a new house's data as input and return those data preprocessed as output.
# Preprocessing: fill the NaNs, handle text data...
# If data doesn't contain the required information, an error should be returned to the user
